#!/usr/bin/env bash
#  Displays "To infinity and beyond" indefinitely with
#  a sleep 2 in between each iteration.
#  Displays "I am invincible!!!" in between each iteration.

i=0
while [ $i -le 3 ]
do
    trap "echo I am invincible!!!" SIGTERM
    echo "To infinity and beyond"
    sleep 2
done
