#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

while IFS= read -r L; do
    echo "$L" | cut -d':' -f1,4,7
done < /etc/passwd
